GET http://localhost:3001/api/phonebook
###
GET http://localhost:3001/info 


###
POST http://localhost:3001/api/phonebook/
Content-Type: application/json

{
 "name": "roman",
 "number": "222"
}
###

###
DELETE http://localhost:3001/api/phonebook/672f7f6043be7eefdf43c7c0

###
PUT http://localhost:3001/api/phonebook/673371a6a2971682ee9f3db8
Content-Type: application/json

{
 "name": "rocco",
 "number": "3333"
}